# Copyright (C) 2004-2015 Cartography Ltd.
# See www.cartotype.com for more information.
#
# A makefile to build CartoType for the Android platform.
# This file lives in <project>/jni for any project using CartoType.
# To build from Windows, use the command <Android-NDK-dir>\ndk-build from the <project> directory.

CARTOTYPE_MAIN := ../../../main

LOCAL_PATH := $(CARTOTYPE_MAIN)

include $(CLEAR_VARS)

LOCAL_LDLIBS := -L$(SYSROOT)/usr/lib -llog

LOCAL_CFLAGS := \
	-I$(CARTOTYPE_MAIN)/base \
	-I$(CARTOTYPE_MAIN)/encryption \
	-I$(CARTOTYPE_MAIN)/framework \
	-I$(CARTOTYPE_MAIN)/freetype_accessor \
	-I$(CARTOTYPE_MAIN)/graphics \
	-I$(CARTOTYPE_MAIN)/image_server \
	-I$(CARTOTYPE_MAIN)/internet \
	-I$(CARTOTYPE_MAIN)/library/expat/lib \
	-I$(CARTOTYPE_MAIN)/library/freetype2/src \
	-I$(CARTOTYPE_MAIN)/library/freetype2/include \
	-I$(CARTOTYPE_MAIN)/library/freetype2/include/freetype \
	-I$(CARTOTYPE_MAIN)/library/freetype2/freetype \
	-I$(CARTOTYPE_MAIN)/library/lpng152 \
	-I$(CARTOTYPE_MAIN)/library/jpeg-8c \
	-I$(CARTOTYPE_MAIN)/library/proj-4.8.0/src \
	-I$(CARTOTYPE_MAIN)/library/sqlite-amalgamation-3080002 \
	-I$(CARTOTYPE_MAIN)/library/twofish \
	-I$(CARTOTYPE_MAIN)/library/zlib-1.2.5 \
	-I$(CARTOTYPE_MAIN)/map \
	-I$(CARTOTYPE_MAIN)/mapdata \
	-I$(CARTOTYPE_MAIN)/projection \
	-I$(CARTOTYPE_MAIN)/router \
	-I$(CARTOTYPE_MAIN)/sqlite_accessor \
	-I$(CARTOTYPE_MAIN)/svg \
	-I$(CARTOTYPE_MAIN)/type1_accessor \
	-I$(CARTOTYPE_MAIN)/tile_accessor \
	-I$(CARTOTYPE_MAIN)/traffic \
	-I$(CARTOTYPE_MAIN)/wms \
	-I$(CARTOTYPE_MAIN)/xml \
	-DSQLITE_ENABLE_RTREE \
	-DSQLITE_RTREE_INT_ONLY \
	-DSQLITE_THREADSAFE=0

LOCAL_MODULE := cartotype

LOCAL_SRC_FILES := \
	platform/android/cartotype_android_java_interface.cpp \
	platform/android/cartotype_android_map_object.cpp \
	platform/android/cartotype_android_route.cpp \
	platform/android/cartotype_android_route_profile.cpp \
	base/cartotype_arithmetic.cpp \
	base/cartotype_array.cpp \
	base/cartotype_base.cpp \
	base/cartotype_bidi.cpp \
	base/cartotype_char.cpp \
	base/cartotype_expression.cpp \
	base/cartotype_list.cpp \
	base/cartotype_stream.cpp \
	base/cartotype_string.cpp \
	base/cartotype_string_tokenizer.cpp \
	base/cartotype_transform.cpp \
	base/cartotype_trie.cpp \
	encryption/cartotype_encrypted_stream.cpp \
	encryption/cartotype_encryption.cpp \
	encryption/cartotype_twofish_encryption.cpp \
	framework/cartotype_framework.cpp \
	freetype_accessor/cartotype_freetype_accessor.cpp \
	graphics/cartotype_16_bit_color_graphics.cpp \
	graphics/cartotype_24_bit_color_graphics.cpp \
	graphics/cartotype_32_bit_color_graphics.cpp \
	graphics/cartotype_8_bit_mono_graphics.cpp \
	graphics/cartotype_aa_render.cpp \
	graphics/cartotype_bitmap.cpp \
	graphics/cartotype_configure.cpp \
	graphics/cartotype_contour.cpp \
	graphics/cartotype_engine.cpp \
	graphics/cartotype_flatten.cpp \
	graphics/cartotype_gradient.cpp \
	graphics/cartotype_graphics.cpp \
	graphics/cartotype_hachure.cpp \
	graphics/cartotype_outline.cpp \
	graphics/cartotype_perspective.cpp \
	graphics/cartotype_spline.cpp \
	graphics/cartotype_typeface.cpp \
	image_server/cartotype_image_server.cpp \
	library/expat/lib/xmlparse.cpp \
	library/expat/lib/xmlrole.cpp \
	library/expat/lib/xmltok.cpp \
	library/freetype2/src/base/ftbase.cpp \
	library/freetype2/src/base/ftdebug.cpp \
	library/freetype2/src/base/ftglyph.cpp \
	library/freetype2/src/base/ftinit.cpp \
	library/freetype2/src/base/ftsystem.cpp \
	library/freetype2/src/psaux/psaux.cpp \
	library/freetype2/src/pshinter/pshinter.cpp \
	library/freetype2/src/psnames/psnames.cpp \
	library/freetype2/src/raster/raster.cpp \
	library/freetype2/src/sfnt/sfnt.cpp \
	library/freetype2/src/smooth/smooth.cpp \
	library/freetype2/src/truetype/truetype.cpp \
	library/freetype2/src/type1/type1.cpp \
	library/twofish/twofish.cpp \
    library/zlib-1.2.5/adler32.cpp \
    library/zlib-1.2.5/compress.cpp \
    library/zlib-1.2.5/crc32.cpp \
    library/zlib-1.2.5/deflate.cpp \
    library/zlib-1.2.5/infback.cpp \
    library/zlib-1.2.5/inffast.cpp \
    library/zlib-1.2.5/inflate.cpp \
    library/zlib-1.2.5/inftrees.cpp \
    library/zlib-1.2.5/trees.cpp \
    library/zlib-1.2.5/uncompr.cpp \
    library/zlib-1.2.5/zutil.cpp \
    library/lpng152/png.cpp \
    library/lpng152/pngerror.cpp \
    library/lpng152/pngget.cpp \
    library/lpng152/pngmem.cpp \
    library/lpng152/pngpread.cpp \
    library/lpng152/pngread.cpp \
    library/lpng152/pngrio.cpp \
    library/lpng152/pngrtran.cpp \
    library/lpng152/pngrutil.cpp \
    library/lpng152/pngset.cpp \
    library/lpng152/pngtrans.cpp \
    library/lpng152/pngwio.cpp \
    library/lpng152/pngwrite.cpp \
    library/lpng152/pngwtran.cpp \
    library/lpng152/pngwutil.cpp \
    library/jpeg-8c/jaricom.cpp \
    library/jpeg-8c/jcapimin.cpp \
    library/jpeg-8c/jcapistd.cpp \
    library/jpeg-8c/jcarith.cpp \
    library/jpeg-8c/jccoefct.cpp \
    library/jpeg-8c/jccolor.cpp \
    library/jpeg-8c/jcdctmgr.cpp \
    library/jpeg-8c/jchuff.cpp \
    library/jpeg-8c/jcinit.cpp \
    library/jpeg-8c/jcmainct.cpp \
    library/jpeg-8c/jcmarker.cpp \
    library/jpeg-8c/jcmaster.cpp \
    library/jpeg-8c/jcomapi.cpp \
    library/jpeg-8c/jcparam.cpp \
    library/jpeg-8c/jcprepct.cpp \
    library/jpeg-8c/jcsample.cpp \
    library/jpeg-8c/jctrans.cpp \
    library/jpeg-8c/jdapimin.cpp \
    library/jpeg-8c/jdapistd.cpp \
    library/jpeg-8c/jdarith.cpp \
    library/jpeg-8c/jdatadst.cpp \
    library/jpeg-8c/jdatasrc.cpp \
    library/jpeg-8c/jdcoefct.cpp \
    library/jpeg-8c/jdcolor.cpp \
    library/jpeg-8c/jddctmgr.cpp \
    library/jpeg-8c/jdhuff.cpp \
    library/jpeg-8c/jdinput.cpp \
    library/jpeg-8c/jdmainct.cpp \
    library/jpeg-8c/jdmarker.cpp \
    library/jpeg-8c/jdmaster.cpp \
    library/jpeg-8c/jdmerge.cpp \
    library/jpeg-8c/jdpostct.cpp \
    library/jpeg-8c/jdsample.cpp \
    library/jpeg-8c/jdtrans.cpp \
    library/jpeg-8c/jerror.cpp \
    library/jpeg-8c/jfdctflt.cpp \
    library/jpeg-8c/jfdctfst.cpp \
    library/jpeg-8c/jfdctint.cpp \
    library/jpeg-8c/jidctflt.cpp \
    library/jpeg-8c/jidctfst.cpp \
    library/jpeg-8c/jidctint.cpp \
    library/jpeg-8c/jmemmgr.cpp \
    library/jpeg-8c/jmemnobs.cpp \
    library/jpeg-8c/jquant1.cpp \
    library/jpeg-8c/jquant2.cpp \
    library/jpeg-8c/jutils.cpp \
	library/proj-4.8.0/src/aasincos.c \
	library/proj-4.8.0/src/adjlon.c	\
	library/proj-4.8.0/src/bch2bps.c \
	library/proj-4.8.0/src/bchgen.c	\
	library/proj-4.8.0/src/biveval.c \
	library/proj-4.8.0/src/dmstor.c	\
	library/proj-4.8.0/src/emess.c \
	library/proj-4.8.0/src/geocent.c \
	library/proj-4.8.0/src/geod.c \
	library/proj-4.8.0/src/geod_for.c \
	library/proj-4.8.0/src/geod_inv.c \
	library/proj-4.8.0/src/geod_set.c \
	library/proj-4.8.0/src/mk_cheby.c \
	library/proj-4.8.0/src/nad_cvt.c \
	library/proj-4.8.0/src/nad_init.c \
	library/proj-4.8.0/src/nad_intr.c \
	library/proj-4.8.0/src/PJ_aea.c \
	library/proj-4.8.0/src/PJ_aeqd.c \
	library/proj-4.8.0/src/PJ_airy.c \
	library/proj-4.8.0/src/PJ_aitoff.c \
	library/proj-4.8.0/src/pj_apply_gridshift.c \
	library/proj-4.8.0/src/pj_apply_vgridshift.c \
	library/proj-4.8.0/src/PJ_august.c \
	library/proj-4.8.0/src/pj_auth.c \
	library/proj-4.8.0/src/PJ_bacon.c \
	library/proj-4.8.0/src/PJ_bipc.c \
	library/proj-4.8.0/src/PJ_boggs.c \
	library/proj-4.8.0/src/PJ_bonne.c \
	library/proj-4.8.0/src/PJ_cass.c \
	library/proj-4.8.0/src/PJ_cc.c \
	library/proj-4.8.0/src/PJ_cea.c \
	library/proj-4.8.0/src/PJ_chamb.c \
	library/proj-4.8.0/src/PJ_collg.c \
	library/proj-4.8.0/src/PJ_crast.c \
	library/proj-4.8.0/src/pj_ctx.c \
	library/proj-4.8.0/src/pj_datums.c \
	library/proj-4.8.0/src/pj_datum_set.c \
	library/proj-4.8.0/src/PJ_denoy.c \
	library/proj-4.8.0/src/pj_deriv.c \
	library/proj-4.8.0/src/PJ_eck1.c \
	library/proj-4.8.0/src/PJ_eck2.c \
	library/proj-4.8.0/src/PJ_eck3.c \
	library/proj-4.8.0/src/PJ_eck4.c \
	library/proj-4.8.0/src/PJ_eck5.c \
	library/proj-4.8.0/src/pj_ellps.c \
	library/proj-4.8.0/src/pj_ell_set.c \
	library/proj-4.8.0/src/PJ_eqc.c \
	library/proj-4.8.0/src/PJ_eqdc.c \
	library/proj-4.8.0/src/pj_errno.c \
	library/proj-4.8.0/src/pj_factors.c \
	library/proj-4.8.0/src/PJ_fahey.c \
	library/proj-4.8.0/src/PJ_fouc_s.c \
	library/proj-4.8.0/src/pj_fwd.c \
	library/proj-4.8.0/src/PJ_gall.c \
	library/proj-4.8.0/src/pj_gauss.c \
	library/proj-4.8.0/src/pj_geocent.c \
	library/proj-4.8.0/src/PJ_geos.c \
	library/proj-4.8.0/src/PJ_gins8.c \
	library/proj-4.8.0/src/PJ_gnom.c \
	library/proj-4.8.0/src/PJ_gn_sinu.c \
	library/proj-4.8.0/src/PJ_goode.c \
	library/proj-4.8.0/src/pj_gridinfo.c \
	library/proj-4.8.0/src/pj_gridlist.c \
	library/proj-4.8.0/src/PJ_gstmerc.c \
	library/proj-4.8.0/src/PJ_hammer.c \
	library/proj-4.8.0/src/PJ_hatano.c \
	library/proj-4.8.0/src/PJ_healpix.c \
	library/proj-4.8.0/src/PJ_igh.c \
	library/proj-4.8.0/src/PJ_imw_p.c \
	library/proj-4.8.0/src/pj_init.c \
	library/proj-4.8.0/src/pj_initcache.c \
	library/proj-4.8.0/src/pj_inv.c \
	library/proj-4.8.0/src/PJ_isea.c \
	library/proj-4.8.0/src/PJ_krovak.c \
	library/proj-4.8.0/src/PJ_labrd.c \
	library/proj-4.8.0/src/PJ_laea.c \
	library/proj-4.8.0/src/PJ_lagrng.c \
	library/proj-4.8.0/src/PJ_larr.c \
	library/proj-4.8.0/src/PJ_lask.c \
	library/proj-4.8.0/src/pj_latlong.c \
	library/proj-4.8.0/src/PJ_lcc.c \
	library/proj-4.8.0/src/PJ_lcca.c \
	library/proj-4.8.0/src/pj_list.c \
	library/proj-4.8.0/src/pj_log.c \
	library/proj-4.8.0/src/PJ_loxim.c \
	library/proj-4.8.0/src/PJ_lsat.c \
	library/proj-4.8.0/src/pj_malloc.c \
	library/proj-4.8.0/src/PJ_mbtfpp.c \
	library/proj-4.8.0/src/PJ_mbtfpq.c \
	library/proj-4.8.0/src/PJ_mbt_fps.c \
	library/proj-4.8.0/src/PJ_merc.c \
	library/proj-4.8.0/src/PJ_mill.c \
	library/proj-4.8.0/src/pj_mlfn.c \
	library/proj-4.8.0/src/PJ_mod_ster.c \
	library/proj-4.8.0/src/PJ_moll.c \
	library/proj-4.8.0/src/pj_msfn.c \
	library/proj-4.8.0/src/pj_mutex.c \
	library/proj-4.8.0/src/PJ_natearth.c \
	library/proj-4.8.0/src/PJ_nell.c \
	library/proj-4.8.0/src/PJ_nell_h.c \
	library/proj-4.8.0/src/PJ_nocol.c \
	library/proj-4.8.0/src/PJ_nsper.c \
	library/proj-4.8.0/src/PJ_nzmg.c \
	library/proj-4.8.0/src/PJ_ob_tran.c \
	library/proj-4.8.0/src/PJ_ocea.c \
	library/proj-4.8.0/src/PJ_oea.c \
	library/proj-4.8.0/src/PJ_omerc.c \
	library/proj-4.8.0/src/pj_open_lib.c \
	library/proj-4.8.0/src/PJ_ortho.c \
	library/proj-4.8.0/src/pj_param.c \
	library/proj-4.8.0/src/pj_phi2.c \
	library/proj-4.8.0/src/PJ_poly.c \
	library/proj-4.8.0/src/pj_pr_list.c \
	library/proj-4.8.0/src/PJ_putp2.c \
	library/proj-4.8.0/src/PJ_putp3.c \
	library/proj-4.8.0/src/PJ_putp4p.c \
	library/proj-4.8.0/src/PJ_putp5.c \
	library/proj-4.8.0/src/PJ_putp6.c \
	library/proj-4.8.0/src/pj_qsfn.c \
	library/proj-4.8.0/src/pj_release.c \
	library/proj-4.8.0/src/PJ_robin.c \
	library/proj-4.8.0/src/PJ_rpoly.c \
	library/proj-4.8.0/src/PJ_sconics.c \
	library/proj-4.8.0/src/PJ_somerc.c \
	library/proj-4.8.0/src/PJ_stere.c \
	library/proj-4.8.0/src/PJ_sterea.c \
	library/proj-4.8.0/src/pj_strerrno.c \
	library/proj-4.8.0/src/PJ_sts.c \
	library/proj-4.8.0/src/PJ_tcc.c \
	library/proj-4.8.0/src/PJ_tcea.c \
	library/proj-4.8.0/src/PJ_tmerc.c \
	library/proj-4.8.0/src/PJ_tpeqd.c \
	library/proj-4.8.0/src/pj_transform.c \
	library/proj-4.8.0/src/pj_tsfn.c \
	library/proj-4.8.0/src/pj_units.c \
	library/proj-4.8.0/src/PJ_urm5.c \
	library/proj-4.8.0/src/PJ_urmfps.c \
	library/proj-4.8.0/src/pj_utils.c \
	library/proj-4.8.0/src/PJ_vandg.c \
	library/proj-4.8.0/src/PJ_vandg2.c \
	library/proj-4.8.0/src/PJ_vandg4.c \
	library/proj-4.8.0/src/PJ_wag2.c \
	library/proj-4.8.0/src/PJ_wag3.c \
	library/proj-4.8.0/src/PJ_wag7.c \
	library/proj-4.8.0/src/PJ_wink1.c \
	library/proj-4.8.0/src/PJ_wink2.c \
	library/proj-4.8.0/src/pj_zpoly1.c \
	library/proj-4.8.0/src/proj_etmerc.c \
	library/proj-4.8.0/src/proj_mdist.c \
	library/proj-4.8.0/src/proj_rouss.c \
	library/proj-4.8.0/src/rtodms.c \
	library/proj-4.8.0/src/vector1.c \
	library/sqlite-amalgamation-3080002/sqlite3.c \
	map/cartotype_address.cpp \
	map/cartotype_label.cpp \
	map/cartotype_map.cpp \
	map/cartotype_map_style.cpp \
	map/cartotype_textbox.cpp \
	mapdata/cartotype_icon.cpp \
	mapdata/cartotype_kml.cpp \
	mapdata/cartotype_map_data.cpp \
	mapdata/cartotype_map_object_cache.cpp \
	mapdata/cartotype_style_sheet.cpp \
	mapdata/cartotype_symbol.cpp \
	projection/cartotype_cylindrical_equidistant.cpp \
	projection/cartotype_mercator.cpp \
	projection/cartotype_projection.cpp \
	router/cartotype_navigator.cpp \
	router/cartotype_router2.cpp \
	router/cartotype_route_info2.cpp \
	router/cartotype_contraction_hierarchy_router.cpp \
	sqlite_accessor/cartotype_sqlite_accessor.cpp \
	svg/cartotype_svg.cpp \
	tile_accessor/cartotype_tile_accessor.cpp \
	traffic/cartotype_openlr.cpp \
	type1_accessor/cartotype_type1_accessor.cpp \
	type1_accessor/cartotype_type1_map_database.cpp \
	type1_accessor/cartotype_type1_map_data_context.cpp \
	type1_accessor/cartotype_type1_text_index.cpp \
	type1_accessor/cartotype_type1_map_object.cpp \
	type1_accessor/cartotype_type1_string_table.cpp \
	wms/cartotype_wms_client.cpp \
	xml/cartotype_sax.cpp

include $(BUILD_SHARED_LIBRARY)

